@SistemaLembretes.Server_HostAddress = http://localhost:5000

### Obter todos os lembretes
GET http://localhost:5000/api/lembrete/todos
Accept: application/json

### Criar um novo lembrete
POST http://localhost:5000/api/lembrete/criarLembrete
Content-Type: application/json

{
  "titulo": "Novo Lembrete",
  "dataLembrete": "2025-01-03T14:00:00",
  "descricao": "Descrição opcional"
}
